services:
    forumhulp.upload_extensions.listener:
        class: forumhulp\upload_extensions\event\listener
        arguments:
            - @config
            - @dbal.conn
            - @auth
            - @template
            - @user
            - %core.root_path%
            - %core.php_ext%
        tags:
            - { name: event.listener }